POST http://localhost:3000/api/users
Content-Type: application/json
Accept: application/json

{
  "username" : "kristo",
  "password" : "kukuruyuk",
  "name" : "gilbertus"
}

###

POST http://localhost:3000/api/users/login
Content-Type: application/json
Accept: application/json

{
  "username" : "kristo",
  "password" : "kukuruyuk"
}

###800f3a16-cf3a-40cf-9220-ca6d1703342b

GET http://localhost:3000/api/users/current
Content-Type: application/json
Accept: application/json
Authorization: ece2219e-230f-4a3f-a83e-ad628bf960cc

###

PATCH http://localhost:3000/api/users/current
Content-Type: application/json
Accept: application/json
Authorization: ece2219e-230f-4a3f-a83e-ad628bf960cc

{
  "name" : "Halo Kristo AKu"
}

###

DELETE http://localhost:3000/api/users/logout
Content-Type: application/json
Accept: application/json
Authorization: ece2219e-230f-4a3f-a83e-ad628bf960cc

###

POST http://localhost:3000/api/contacts
Content-Type: application/json
Accept: application/json
Authorization: 756b024a-5bce-4d76-b465-39759cc68d2f

{
  "first_name" : "Joko",
  "last_name" : "Morro",
  "email" : "gilbertuskristo@gmail.com",
  "phone" : "324234234234"
}

###

GET http://localhost:3000/api/contacts
Content-Type: application/json
Accept: application/json
Authorization: 756b024a-5bce-4d76-b465-39759cc68d2f

###

GET http://localhost:3000/api/contacts/1
Content-Type: application/json
Accept: application/json
Authorization: 756b024a-5bce-4d76-b465-39759cc68d2f

### Update

PUT http://localhost:3000/api/contacts/1
Content-Type: application/json
Accept: application/json
Authorization: 756b024a-5bce-4d76-b465-39759cc68d2f

{
  "first_name": "yanto",
  "last_name": "balap",
  "email": "yantobalap@gmail.com",
  "phone": "324234234234"
}

### Delete Contact

DELETE http://localhost:3000/api/contacts/1
Content-Type: application/json
Accept: application/json
Authorization: 756b024a-5bce-4d76-b465-39759cc68d2f